#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  external_bar all:30:0 \
  menubar_opacity 1.0 \
  mouse_follows_focus true \
  focus_follows_mouse false \
  display_arrangement_order default \
  window_origin_display focused \
  window_placement second_child \
  window_insertion_point focused \
  window_zoom_persist off \
  window_shadow float \
  window_opacity on \
  window_opacity_duration 0.2 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_animation_duration 0.5 \
  window_animation_easing ease_out_quint \
  insert_feedback_color 0xff000000 \
  split_ratio 0.50 \
  split_type auto \
  auto_balance true \
  top_padding 08 \
  bottom_padding 08 \
  left_padding 08 \
  right_padding 08 \
  window_gap 10 \
  layout bsp \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# spaces
yabai -m space 1 --label terminal
yabai -m space 2 --label browser
yabai -m space 3 --label communication
yabai -m space 4 --label video
yabai -m space 5 --label nsfw

###############################################################################
# SIGNALS
###############################################################################
# Focus it when a window is created
# yabai -m signal --add event=window_created action="yabai -m window --focus \$YABAI_WINDOW_ID && sketchybar --trigger yabai_window_change"
# # When one window is closed, focus shifts to another window in the same space. If it is the last window, nothing happens.
# yabai -m signal --add event=window_destroyed action='
# win=$(yabai -m query --windows --space | jq -r --argjson d "$YABAI_WINDOW_ID" "map(select(.id != \$d)) | if length > 0 then .[0].id else empty end");
# if [ -n "$win" ]; then yabai -m window --focus "$win"; fi && sketchybar --trigger yabai_window_change
# '

yabai -m signal --add event=window_created action="sketchybar --trigger yabai_window_change"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger yabai_window_change"

# window_focused
yabai -m signal --add event=window_focused action="sketchybar --trigger yabai_window_change"
# window_moved
yabai -m signal --add event=window_moved action="sketchybar --trigger yabai_window_change"
# space_changed
yabai -m signal --add event=space_created action="sketchybar --trigger yabai_space_change"
yabai -m signal --add event=space_destroyed action="sketchybar --trigger yabai_space_change"
yabai -m signal --add event=space_changed action="sketchybar --trigger yabai_space_change && sketchybar --trigger yabai_window_change"

###############################################################################
# RULES
###############################################################################
yabai -m rule --add app="^(Alacritty|Ghostty|WezTerm|kitty|Terminal)$" space=^terminal
yabai -m rule --add app="^(Safari|Zen|Brave|Google Chrome|Chromium|Firefox|Vivaldi|Opera|Microsoft Edge)$" space=^browser
yabai -m rule --add app="^(Mail|WeChat|Feishu|Discord|QQ)$" space=^communication

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|Raycast|Raycast Beta|Karabiner-Elements|Karabiner-EventViewer|Music|CleanMyMac|Surge|MediaMate|Pritunl|Claude|Surge Dashboard|Preview|Quantumult X)$" manage=off sub-layer=below
yabai -m rule --add label="Finder" app="^Finder$" manage=off sub-layer=below
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off sub-layer=below
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off sub-layer=below
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off sub-layer=below
yabai -m rule --add app="Parallels Desktop" title="(Configuration|Control Center|Preferences)$" manage=off sub-layer=below
yabai -m rule --add app="WeChat" title!="^Weixin$" manage=off sub-layer=below
yabai -m rule --add app="QQ" title!="'QQ" manage=off sub-layer=below
yabia -m rule --add app="^(MuMu Android Device|MuMuPlayer Pro)$" manage=off sub-layer=below
yabai -m rule --add app="ChatGPT" manage=off sub-layer=below
yabai -m rule --add app="Antigravity" title="Settings" manage=off sub-layer=below
yabai -m rule --add app="CC Switch" manage=off sub-layer=below
yabai -m rule --add app="Gemini" manage=off sub-layer=below
