# Go to the N window in tmux in tmux it is Ctrl+b+number
map cmd+1   send_text normal,application \x021
map cmd+2   send_text normal,application \x022
map cmd+3   send_text normal,application \x023
map cmd+4   send_text normal,application \x024
map cmd+5   send_text normal,application \x025
map cmd+6   send_text normal,application \x026
map cmd+7   send_text normal,application \x027
map cmd+8   send_text normal,application \x028
map cmd+9   send_text normal,application \x029

# New tmux window on Cmd+t in tmux it is Ctrl+b+c
map cmd+t   send_text normal,application \x02c

# Close tmux pane on Cmd+w in tmux it is Ctrl+b+x
map cmd+w   send_text normal,application \x02x

# Go to the left tab on Cmd+[ in tmux it is Ctrl+b+p
map cmd+[   send_text normal,application \x02p

# Go to the right tab on Cmd+] in tmux it is Ctrl+b+n
map cmd+]   send_text normal,application \x02n

# Go to the previous client on Cmd+{ in tmux it is Ctrl+b+(
map cmd+shift+[   send_text normal,application \x02(

# Go to the next client on Cmd+} in tmux it is Ctrl+b+)
map cmd+shift+]   send_text normal,application \x02)

# Go to the last tab on Cmd+l in tmux it is Ctrl+b+l
map cmd+l   send_text normal,application \x02l

# Go to the last client on Cmd+; in tmux it is Ctrl+b+L
map cmd+shift+l   send_text normal,application \x02L

# Open window list panel on Cmd+` in tmux it is Ctrl+b+w
map cmd+`   send_text normal,application \x02w

# Split Window Horizontally on Cmd+\ in tmux it is Ctrl+b+"
map cmd+0x2a   send_text normal,application \x02"

# Split Window Vertically on Cmd+| in tmux it is Ctrl+b+%
map cmd+shift+0x2a   send_text normal,application \x02%

# Go to copy mode on Cmd+u in tmux it is Ctrl+b+[
map cmd+u   send_text normal,application \x02[

# Resize-pane -Z on Cmd+z in tmux it is Ctrl+b+z
map cmd+z   send_text normal,application \x02z
