# prevent various problems related to keybindings caused by the plugin sourcing sequenc
# completions from brew
autoload -Uz compinit
zcd="${ZDOTDIR:-$HOME}/.zcompdump"
compinit -d "$zcd"
[[ -f "$zcd.zwc" && "$zcd" -nt "$zcd.zwc" ]] || zcompile "$zcd" 2>/dev/null
unset zcd

# yazi shell wrapper
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

source ~/.config/zsh/env_keys.zsh
source ~/.config/zsh/alias.zsh
source ~/.config/zsh/vim-mode.zsh
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source <(fzf --zsh)

bindkey '\C-y' autosuggest-accept

export PATH="$HOME/.local/bin:$PATH"
. "/Users/smoose/.deno/env"

export PATH="/Users/smoose/.local/share/tmux/plugins/tmuxifier/bin:$PATH"
export PATH="/Users/smoose/go/bin:$PATH"

export STARSHIP_CONFIG=~/.config/starship/starship.toml # starship config path
export EDITOR="nvim"
export LDFLAGS="-L/opt/homebrew/lib"
export CPPFLAGS="-I/opt/homebrew/include"
export TMUXIFIER_LAYOUT_PATH="$HOME/.config/tmux/layouts"

export NVM_DIR="$HOME/.nvm"
# 补全文件开头会 command -v nvm，查不到就直接 return，所以先放个占位
nvm() { : }
. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
nvm() {
  unfunction nvm
  \. "/opt/homebrew/opt/nvm/nvm.sh"
  nvm "$@"
}

# bun completions
[ -s "/Users/smoose/.bun/_bun" ] && source "/Users/smoose/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# opencode
export OPENCODE_ENABLE_EXA=1

export TMUXIFIER="$HOME/.local/share/tmux/plugins/tmuxifier"
source "$TMUXIFIER/init.sh"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

fuck() {
  unfunction fuck
  eval "$(thefuck --alias)"
  fuck "$@"
}

fastfetch
