color0 #262e3d
color1 #FF738A
color2 #3CEC85
color3 #EACD61
color4 #69C3FF
color5 #22ECDB
color6 #77aed7
color7 #c3cfd9
color8 #444c5b
color9 #FF738A
color10 #3CEC85
color11 #EACD61
color12 #69C3FF
color13 #22ECDB
color14 #77aed7
color15 #ABB7C1
background #1c2433
foreground #c3cfd9
cursor #c3cfd9
cursor_text_color #1c2433
selection_background #444c5b
selection_foreground #c3cfd9
