[general]
import = [
    "~/.config/alacritty/theme.toml",
    "~/.config/alacritty/mappings.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 1.0
option_as_alt = "OnlyLeft"
padding = { x = 0, y = 0 }
dynamic_padding = true

[font]
normal = { family = "Maple Mono NF", style = "Thin" }
size = 13

[mouse]
hide_when_typing = true
