
[colors.primary]
background = "#fafafa"
foreground = "#383a42"
dim_foreground = "#d7d7d8"
bright_foreground = "#202227"

[colors.cursor]
text = "#fafafa"
cursor = "#383a42"

[colors.vi_mode_cursor]
text = "#fafafa"
cursor = "#383a42"

[colors.search.matches]
foreground = "#fafafa"
background = "#50a14f"

[colors.search.focused_match]
foreground = "#fafafa"
background = "#4078f2"

[colors.footer_bar]
foreground = "#fafafa"
background = "#50a14f"

[colors.hints.start]
foreground = "#fafafa"
background = "#c18401"

[colors.hints.end]
foreground = "#fafafa"
background = "#d75f00"

[colors.selection]
text = "#fafafa"
background = "#383a42"

[colors.normal]
black = "#f4f4f4"
red = "#d84a3d"
green = "#50a14f"
yellow = "#c18401"
blue = "#4078f2"
magenta = "#a626a4"
cyan = "#0070a8"
white = "#383a42"

[colors.bright]
black = "#dfdfe0"
red = "#d84a3d"
green = "#50a14f"
yellow = "#c18401"
blue = "#4078f2"
magenta = "#a626a4"
cyan = "#0070a8"
white = "#090a0b"


[[colors.indexed_colors]]
index = 16
color = "#986801"

