[colors.primary]
background = "#111827"
foreground = "#F3F4F6"
dim_foreground = "#3e4554"
bright_foreground = "#E5E7EB"

[colors.cursor]
text = "#111827"
cursor = "#F3F4F6"

[colors.vi_mode_cursor]
text = "#111827"
cursor = "#F3F4F6"

[colors.search.matches]
foreground = "#111827"
background = "#B5E8B0"

[colors.search.focused_match]
foreground = "#111827"
background = "#BAE6FD"

[colors.footer_bar]
foreground = "#111827"
background = "#B5E8B0"

[colors.hints.start]
foreground = "#111827"
background = "#FBC19D"

[colors.hints.end]
foreground = "#111827"
background = "#E8D4B0"

[colors.selection]
text = "#111827"
background = "#F3F4F6"

[colors.normal]
black = "#1e2534"
red = "#DDD6FE"
green = "#B5E8B0"
yellow = "#FBC19D"
blue = "#BAE6FD"
magenta = "#FCA5A5"
cyan = "#BAE6FD"
white = "#F3F4F6"

[colors.bright]
black = "#323948"
red = "#DDD6FE"
green = "#B5E8B0"
yellow = "#FBC19D"
blue = "#BAE6FD"
magenta = "#FCA5A5"
cyan = "#BAE6FD"
white = "#D1D5DB"

[[colors.indexed_colors]]
index = 16
color = "#9CA3AF"
