
[colors.primary]
background = "#fff9e8"
foreground = "#495157"
dim_foreground = "#ddd7c6"
bright_foreground = "#3b4349"

[colors.cursor]
text = "#fff9e8"
cursor = "#495157"

[colors.vi_mode_cursor]
text = "#fff9e8"
cursor = "#495157"

[colors.search.matches]
foreground = "#fff9e8"
background = "#d59600"

[colors.search.focused_match]
foreground = "#fff9e8"
background = "#87a060"

[colors.footer_bar]
foreground = "#fff9e8"
background = "#d59600"

[colors.hints.start]
foreground = "#fff9e8"
background = "#8da101"

[colors.hints.end]
foreground = "#fff9e8"
background = "#b67996"

[colors.selection]
text = "#fff9e8"
background = "#495157"

[colors.normal]
black = "#f6f0df"
red = "#5f9b93"
green = "#d59600"
yellow = "#8da101"
blue = "#87a060"
magenta = "#c85552"
cyan = "#ef615e"
white = "#495157"

[colors.bright]
black = "#e5dfce"
red = "#5f9b93"
green = "#d59600"
yellow = "#8da101"
blue = "#87a060"
magenta = "#c85552"
cyan = "#ef615e"
white = "#272f35"


[[colors.indexed_colors]]
index = 16
color = "#c85552"

