
[colors.primary]
background = "#1c2433"
foreground = "#c3cfd9"
dim_foreground = "#a1adb7"
bright_foreground = "#ABB7C1"

[colors.cursor]
text = "#1c2433"
cursor = "#c3cfd9"

[colors.vi_mode_cursor]
text = "#1c2433"
cursor = "#c3cfd9"

[colors.search.matches]
foreground = "#1c2433"
background = "#3CEC85"

[colors.search.focused_match]
foreground = "#1c2433"
background = "#69C3FF"

[colors.footer_bar]
foreground = "#1c2433"
background = "#3CEC85"

[colors.hints.start]
foreground = "#1c2433"
background = "#EACD61"

[colors.hints.end]
foreground = "#1c2433"
background = "#FF955C"

[colors.selection]
text = "#1c2433"
background = "#c3cfd9"

[colors.normal]
black = "#262e3d"
red = "#FF738A"
green = "#3CEC85"
yellow = "#EACD61"
blue = "#69C3FF"
magenta = "#22ECDB"
cyan = "#77aed7"
white = "#c3cfd9"

[colors.bright]
black = "#444c5b"
red = "#FF738A"
green = "#3CEC85"
yellow = "#EACD61"
blue = "#69C3FF"
magenta = "#22ECDB"
cyan = "#77aed7"
white = "#08bdba"


[[colors.indexed_colors]]
index = 16
color = "#B78AFF"

