"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#dcd0eb)\
$os\
[](bg:#c4a7e7 fg:#dcd0eb)\
$directory\
[](fg:#c4a7e7 bg:#534867)\
$git_branch\
$git_status\
[](fg:#534867 bg:#171520)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#171520 bg:#13111b)\
$time\
[ ](fg:#13111b)\
\n$character"""

[directory]
style = "fg:#4d415c bg:#c4a7e7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#534867"
format = '[[ $symbol $branch ](fg:#c4a7e7 bg:#534867)]($style)'

[git_status]
style = "bg:#534867"
format = '[[($all_status$ahead_behind )](fg:#c4a7e7 bg:#534867)]($style)'

[nodejs]
symbol = ""
style = "bg:#171520"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#171520)]($style)'

[bun]
symbol = ""
style = "bg:#171520"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#171520)]($style)'

[rust]
symbol = ""
style = "bg:#171520"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#171520)]($style)'

[golang]
symbol = ""
style = "bg:#171520"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#171520)]($style)'

[php]
symbol = ""
style = "bg:#171520"
format = '[[ $symbol ($version) ](fg:#c4a7e7 bg:#171520)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#13111b"
format = '[[  $time ](fg:#c4a7e7 bg:#13111b)]($style)'

[os]
style = "bg:#dcd0eb fg:#423d47"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
