"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#b2d6d1)\
$os\
[](bg:#7fbbb3 fg:#b2d6d1)\
$directory\
[](fg:#7fbbb3 bg:#496063)\
$git_branch\
$git_status\
[](fg:#496063 bg:#272e33)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#272e33 bg:#20262b)\
$time\
[ ](fg:#20262b)\
\n$character"""

[directory]
style = "fg:#2e4844 bg:#7fbbb3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#496063"
format = '[[ $symbol $branch ](fg:#96c4be bg:#496063)]($style)'

[git_status]
style = "bg:#496063"
format = '[[($all_status$ahead_behind )](fg:#96c4be bg:#496063)]($style)'

[nodejs]
symbol = ""
style = "bg:#272e33"
format = '[[ $symbol ($version) ](fg:#7fbbb3 bg:#272e33)]($style)'

[bun]
symbol = ""
style = "bg:#272e33"
format = '[[ $symbol ($version) ](fg:#7fbbb3 bg:#272e33)]($style)'

[rust]
symbol = ""
style = "bg:#272e33"
format = '[[ $symbol ($version) ](fg:#7fbbb3 bg:#272e33)]($style)'

[golang]
symbol = ""
style = "bg:#272e33"
format = '[[ $symbol ($version) ](fg:#7fbbb3 bg:#272e33)]($style)'

[php]
symbol = ""
style = "bg:#272e33"
format = '[[ $symbol ($version) ](fg:#7fbbb3 bg:#272e33)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#20262b"
format = '[[  $time ](fg:#7fbbb3 bg:#20262b)]($style)'

[os]
style = "bg:#b2d6d1 fg:#313d3c"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
