"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#c0d6e4)\
$os\
[](bg:#69c3ff fg:#c0d6e4)\
$directory\
[](fg:#69c3ff bg:#375977)\
$git_branch\
$git_status\
[](fg:#375977 bg:#19202e)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#19202e bg:#151b26)\
$time\
[ ](fg:#151b26)\
\n$character"""

[directory]
style = "fg:#264e69 bg:#69c3ff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#375977"
format = '[[ $symbol $branch ](fg:#69c3ff bg:#375977)]($style)'

[git_status]
style = "bg:#375977"
format = '[[($all_status$ahead_behind )](fg:#69c3ff bg:#375977)]($style)'

[nodejs]
symbol = ""
style = "bg:#19202e"
format = '[[ $symbol ($version) ](fg:#69c3ff bg:#19202e)]($style)'

[bun]
symbol = ""
style = "bg:#19202e"
format = '[[ $symbol ($version) ](fg:#69c3ff bg:#19202e)]($style)'

[rust]
symbol = ""
style = "bg:#19202e"
format = '[[ $symbol ($version) ](fg:#69c3ff bg:#19202e)]($style)'

[golang]
symbol = ""
style = "bg:#19202e"
format = '[[ $symbol ($version) ](fg:#69c3ff bg:#19202e)]($style)'

[php]
symbol = ""
style = "bg:#19202e"
format = '[[ $symbol ($version) ](fg:#69c3ff bg:#19202e)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#151b26"
format = '[[  $time ](fg:#69c3ff bg:#151b26)]($style)'

[os]
style = "bg:#c0d6e4 fg:#383f44"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
