# features +ss02: 打断==
font_family family="Lilex Nerd Font Mono" features="+ss02"

# 1. 映射 Nerd Font 图标区：强制让 Kitty 使用 Lilex Nerd Font 来渲染所有图标
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF Lilex Nerd Font

# 2. 备用微调：后面的数字代表图标放大倍数，貌似只有1,2可用
# narrow_symbols U+E000-U+F8FF,U+F0000-U+FFFFF 2 
